<?php

namespace App\Enumerators;

enum ConstantType: string
{
    case DISCORD_ID = 'DISCORD_ID';
    case DISCORD_CHANNEL = 'DISCORD_CHANNEL';
    case DISCORD_MAIN_CHANNEL = 'DISCORD_MAIN_CHANNEL';
    case DISCORD_SUPPORT_CHANNEL = 'DISCORD_SUPPORT_CHANNEL';
    case DISCORD_LINK = 'DISCORD_LINK';

    case CONTACT_EMAIL = 'CONTACT_EMAIL';
    case CONTACT_PHONE = 'CONTACT_PHONE';
    
    case DISCORD_CONTACT_PAYPAL = 'DISCORD_CONTACT_PAYPAL';
    case DISCORD_CONTACT_PAYPAL_USER = 'DISCORD_CONTACT_PAYPAL_USER';

    case MONTHLY_GOAL = 'MONTHLY_GOAL';
    case PAYSERA_NUMBER = 'PAYSERA_NUMBER';

    case MESSAGE_FOR_PARENTS = 'MESSAGE_FOR_PARENTS';
}
